export const AWAY_PING_INTERVAL = 5000;
export const HOME_PING_INTERVAL = 60 * 1000;
export const CHANGE_PING_INTERVAL = 1000;
export const AWAY_MIN_CONSECUTIVE_PINGS = 20;
export const GRACE_PERIOD_PINGS = 60;
