name: 'Format, lint and check for code errors'

on:
    push:
        paths-ignore:
            - '**.md'
    schedule:
        - cron: '0 0 1 * *'
    create:
        tags:
            - '*'

jobs:
    lint-and-tsc:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1

            - name: Node
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Install
              run: yarn

            - name: Format
              run: yarn format-check

            - name: Lint
              run: yarn lint

            - name: TypeScript
              run: yarn compile
